# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_csv <- function(filepath) {
    .Call(`_MassiveTable_read_csv`, filepath)
}

process_line <- function(start, end) {
    invisible(.Call(`_MassiveTable_process_line`, start, end))
}

process_csv_line <- function(start, end) {
    invisible(.Call(`_MassiveTable_process_csv_line`, start, end))
}

read_csv_mmap <- function(filepath) {
    .Call(`_MassiveTable_read_csv_mmap`, filepath)
}

