# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_MTTable <- function() {
    .Call(`_Bigmem2_create_MTTable`)
}

r_initiateMTTable <- function(xp, r_filepath) {
    .Call(`_Bigmem2_r_initiateMTTable`, xp, r_filepath)
}

test_subtable <- function() {
    .Call(`_Bigmem2_test_subtable`)
}

read_csv <- function(filepath) {
    .Call(`_Bigmem2_read_csv`, filepath)
}

process_line <- function(start, end) {
    invisible(.Call(`_Bigmem2_process_line`, start, end))
}

process_csv_line <- function(start, end) {
    invisible(.Call(`_Bigmem2_process_csv_line`, start, end))
}

read_csv_mmap <- function(filepath) {
    .Call(`_Bigmem2_read_csv_mmap`, filepath)
}

